[
 "many an daft kitten makes a wise cat.",
 "a mouth full of water can't blow a fire.",
 "crows feet are always on the ground.",
 "there is nothing so eloquent as a rattlesnake's tail.",
 "the paddle which you find in the canoe is the one that will take you across.",
 "listen to him who has four ears.",
 "a monk cannot shave his own head.",
 "the year is long and one eats every day.",
 "he who has the luck brings home the bride.",
 "let him who owns the cow take her tail.",
 "no sleep, no dream.",
 "to get out a rusty nail, you must take away a piece of the wall.",
 "what you have put into your kettle comes into your spoon.",
 "grey jackals know each other by their speckles.",
 "he that examines every bush will barely get into the woods.",
 "he who rides the mule shoes her.",
 "a glass of wine will improve your mind.",
 "one elephant can't stir up much dust.",
 "an old man's sayings are seldom untrue.",
 "he who is held by the thoat cannot swallow.",
 "if a few sen do not go, many sen will not come.",
 "the hand that holds a sword should be kissed.",
 "when you eat a round cake you begin at the center.",
 "so much dough, so many buns.",
 "gibberish does not a proverb make.",
 "a full belly sets a man giggling.",
 "beware of women with beards and men without them.",
 "there is no use trying to tug a glacier backwards.",
 "for the sake of the grease, the cat licks the candlestick.",
 "the nose does not always go in front.",
 "the ox spoke and said, 'moo.'",
 "keep an eye on your rear wheels.",
 "thrash the apprentice while he has not yet broken the water jug.",
 "it is hard to put many heads under one hat.",
 "no-a-days mens eyelids are thin.",
 "one does not look at the moon when the sun is up.",
 "if you owe a dog anything, call him Sir.",
 "nothing enters into a closed hand.",
 "a load of salt on another man's head is easily carried."
 "ant follows fat, fat drowns ant.",
]
